### ISSUE TITLE
Enhancement Proposal: Footer Design

### ISSUE THREAD

**Issue by SHARITHA2002** [MAVRICK-1/causewaylogin#10]
## Issue Description:

The proposed enhancement involves revamping the footer of the website to improve its functionality, aesthetics, and user experience. 

## Current Behavior:

Currently, the footer remains sticky while scrolling up, which can sometimes disrupt the user experience.

![image](https://github.com/MAVRICK-1/causewaylogin/assets/100562754/cc618796-f4fe-4627-8794-78e758d12c2a)

## Expected Behavior:

Modify the footer to provide a smoother and more intuitive user experience. Enhance the visual appearance of the footer to better match the overall theme and design language of the website.

Would it be possible for you to assign me this issue? I'm eager to collaborate and help improve the Codebin website.

Looking forward to your response.

Best regards,
Sharitha G
(GSSOC'24 Contributor)

**Comment by MAVRICK-1** [comment]
@SHARITHA2002 thanx for your idea , but unfortunately, I withdraw this project from GirlScript Summer of code . It will be removed within few days
