### ISSUE TITLE
Improvement in navbar adding logo( name of project in navbar  )

### ISSUE THREAD

**Issue by Adeesh-bode** [MAVRICK-1/causewaylogin#14]
The issue involves an improvement to the existing navigation bar by adding a logo that includes the name of the project. This enhancement aims to increase brand recognition and improve the aesthetic appeal of the website or application. The task would include designing a suitable logo that aligns with the project's branding guidelines, integrating the logo into the navbar in a way that is visually appealing and functional across different devices and screen sizes, and ensuring that the logo is properly linked to the homepage for easy navigation.

**Comment by MAVRICK-1** [comment]
@Adeesh-bode thanx for your idea , but unfortunately, I withdraw this project from GirlScript Summer of code . It will be removed within few days
