### ISSUE TITLE
[BUG] Delete .vscode folder

### ISSUE THREAD

**Issue by say-het** [MAVRICK-1/causewaylogin#15]
**Description**

 - Issue is that ".vscode" folder is not necessary folder.
 - It depends on system so it creates conflicts with user's existing Extensions, as not every user have same extensions.

I would like to work on this issue please assign it to me under GSSoC'24 @MAVRICK-1 

Little about me : I am experienced contributor as I have completed _Hacktoberfest-2020_ and _Hactoberfest-2023_ successfully.

**Comment by MAVRICK-1** [comment]
@say-het this project is excluded
