### ISSUE TITLE
Little update in CSS to reduce the redundancy.

### ISSUE THREAD

**Issue by say-het** [MAVRICK-1/causewaylogin#16]
**Description**

 - I have updated to better CSS to reduce the redundancy in style.css file.

I have already fixed it can you assign me this issue under GSSoC'24 @MAVRICK-1 So that I can raise a PR.

Little about me : I am experienced contributor as I have completed _Hacktoberfest-2020_ and _Hactoberfest-2023_ successfully.

**Comment by MAVRICK-1** [comment]
@say-het this project is excluded from Gssoc
