### ISSUE TITLE
Add Code of Conduct 

### ISSUE THREAD

**Issue by aasthakourav20** [MAVRICK-1/causewaylogin#17]
Hey @MAVRICK-1 We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by MAVRICK-1** [comment]
@aasthakourav20 this project has been withdraw from gssoc

**Comment by aasthakourav20** [comment]
But why ?

**Comment by MAVRICK-1** [comment]
@aasthakourav20 I submitted the Codebin project for the MLH Code Snippet, but it hasn't been reviewed by the MLH team yet,
so i have to withdraw it , but also got another project https://github.com/MAVRICK-1/e-commerce_website
