### ISSUE TITLE
footer and contact us page

### ISSUE THREAD

**Issue by NitinChakrawarti** [MAVRICK-1/causewaylogin#19]
In website footer has nothing  that much  and also it has missing contact us section 
@MAVRICK-1 assign this issue to me i can design both things for website.

![Screenshot 2024-05-13 204013](https://github.com/MAVRICK-1/causewaylogin/assets/149225785/c42bfe83-c8a9-46c7-b54c-7104d9c14795)

**Comment by Shravani246** [comment]
@NitinChakrawarti Please assign me this issue. I can complete it.
