### ISSUE TITLE
Missing Code of Conduct & Contribution.md

### ISSUE THREAD

**Issue by Dhruv-Pattel** [MAVRICK-1/causewaylogin#9]
This repository has no Code of conduct & Contribution.md file. any open-source project needs to set clear standards for behavior. It promotes inclusivity, prevents misconduct, fosters accountability, and maintains a positive environment.

Please assign this issue to me.

**Comment by MAVRICK-1** [comment]
@Dhruv-Pattel thanx,but unfortunately, I withdraw this project from GirlScript Summer of code . It will be removed within few days
